kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47.2,)
kff_version=4.11.0

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=stardust
mod_name=Stardust
mod_version=5.4.2
mod_authors=NoahOnFyre
mod_description=Enhancing the vanilla enchanting system with various more enchantments and related mechanics.
mod_license=MIT
mod_group_id=com.nyronium.stardust
